server:
  port: 8091

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/SocialMediaUserDb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  feign:
    auth: http://localhost:8091/api/v1/auth
    post: http://localhost:8092/api/v1/post
