server:
  port: 8092

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service
  data:
    mongodb:
      host: localhost
      port: 28000
      username: "SocialMediaAdmin"
      password: "123456789"
      database: SocialMediaPostDB

myapplication:
  feign:
    auth: http://localhost:8090/api/v1/auth
    user: http://localhost:8091/api/v1/user
    elastic: http://localhost:8099/api/v1/elastic



